package com.example.mybookshopapp.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author entity")
public class Author implements Serializable {

    @Id
    @SequenceGenerator(name = "seq_author_id", sequenceName = "seq_author_id", initialValue = 1001, allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_author_id")
    @ApiModelProperty(value = "author id generated by bd", position = 1)
    private Integer id;

    @ApiModelProperty(value = "name of author", example = "Bob Blaskovits", position = 2)
    private String name;

    @ApiModelProperty(value = "link to photo of author", example = "Bob Blaskovits", position = 3)
    private String photo;

    @ApiModelProperty(value = "mnemonic identifier of author", position = 5)
    private String slug;

    @ApiModelProperty(value = "description (biography, characteristics) of author", position = 4)
    @Column(columnDefinition = "TEXT")
    private String description;

    public Author(List<String> authors) {
        if (authors != null) {
            this.name = authors.toString();
        }
    }

    public Author() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String firstName) {
        this.name = firstName;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return name;
    }


}
