
INSERT INTO authors (first_name, second_name) values ('Drucie', 'Goodbourn');
INSERT INTO authors (first_name, second_name) values ('Marcia', 'Aggiss');
INSERT INTO authors (first_name, second_name) values ('Giovanni', 'Bigg');
INSERT INTO authors (first_name, second_name) values ('Duffie', 'Eynon');
INSERT INTO authors (first_name, second_name) values ('Anselma', 'McKennan');
INSERT INTO authors (first_name, second_name) values ('Gert', 'Kira');
INSERT INTO authors (first_name, second_name) values ('Clerc', 'Djakovic');
INSERT INTO authors (first_name, second_name) values ('Stacee', 'Elsy');
INSERT INTO authors (first_name, second_name) values ('Dorotea', 'Bonhill');
INSERT INTO authors (first_name, second_name) values ('Minni', 'Bunney');
INSERT INTO authors (first_name, second_name) values ('Berty', 'Gandley');
INSERT INTO authors (first_name, second_name) values ('Raynard', 'Tesdale');
INSERT INTO authors (first_name, second_name) values ('Joanna', 'Hutfield');
INSERT INTO authors (first_name, second_name) values ('Dannie', 'Glidder');
INSERT INTO authors (first_name, second_name) values ('Timmie', 'Adshede');
INSERT INTO authors (first_name, second_name) values ('Fernando', 'Neads');
INSERT INTO authors (first_name, second_name) values ('Teddy', 'Guilliland');
INSERT INTO authors (first_name, second_name) values ('Paloma', 'Grebert');
INSERT INTO authors (first_name, second_name) values ('Kristos', 'Usher');
INSERT INTO authors (first_name, second_name) values ('Darcey', 'Rohmer');
INSERT INTO authors (first_name, second_name) values ('Cristie', 'Isacsson');
INSERT INTO authors (first_name, second_name) values ('Lindsay', 'Coutthart');
INSERT INTO authors (first_name, second_name) values ('Helyn', 'Schneidar');
INSERT INTO authors (first_name, second_name) values ('Bette-ann', 'Askem');
INSERT INTO authors (first_name, second_name) values ('Dom', 'Robuchon');


insert into books (author, title, priceOld, price, author_id) values ('Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37', 1);
insert into books (author, title, priceOld, price, author_id) values ('Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96', 2);
insert into books (author, title, priceOld, price, author_id) values ('Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04', 3);
insert into books (author, title, priceOld, price, author_id) values ('Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40', 4);
insert into books (author, title, priceOld, price, author_id) values ('Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44', 5);
insert into books (author, title, priceOld, price, author_id) values ('Gert Kira', 'architect vertical ROI', '$282.54', '$102.61', 6);
insert into books (author, title, priceOld, price, author_id) values ('Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27', 7);
insert into books (author, title, priceOld, price, author_id) values ('Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96', 8);
insert into books (author, title, priceOld, price, author_id) values ('Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25', 9);
insert into books (author, title, priceOld, price, author_id) values ('Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69', 10);
insert into books (author, title, priceOld, price, author_id) values ('Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98', 11);
insert into books (author, title, priceOld, price, author_id) values ('Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06', 12);
insert into books (author, title, priceOld, price, author_id) values ('Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97', 13);
insert into books (author, title, priceOld, price, author_id) values ('Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52', 14);
insert into books (author, title, priceOld, price, author_id) values ('Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83', 15);
insert into books (author, title, priceOld, price, author_id) values ('Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89', 16);
insert into books (author, title, priceOld, price, author_id) values ('Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21', 17);
insert into books (author, title, priceOld, price, author_id) values ('Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76', 18);
insert into books (author, title, priceOld, price, author_id) values ('Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71', 19);
insert into books (author, title, priceOld, price, author_id) values ('Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01', 20);
insert into books (author, title, priceOld, price, author_id) values ('Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25', 21);
insert into books (author, title, priceOld, price, author_id) values ('Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31', 22);
insert into books (author, title, priceOld, price, author_id) values ('Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86', 23);
insert into books (author, title, priceOld, price, author_id) values ('Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15', 24);
insert into books (author, title, priceOld, price, author_id) values ('Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48', 25);
